<a href="https://colab.research.google.com/github/maryamthabit/assignment/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
market=pd.read_csv("marketplace.csv")

In [17]:
market

,date,sku_name,product_id,merchant_code,merchant_badge,product_type,merchant_city,cod,price,stock,daily_gmv,daily_sold,daily_view,rating,total_review,total_sold
0,3/11/2020,HUAWEI NOVA 5T RAM 8GB INTERNAL 128GB,E1,1.0,PM,Huawei nova 5T,Kota Kediri,False,4500000,1,0,0,0,95,37,74
1,3/26/2020,Huawei Nova 5T (8GB/128GB) - Crush Green,F1,2.0,OS,Huawei nova 5T,Kota Administrasi Jakarta Utara,False,4999000,5,0,0,0,0,0,2
2,3/23/2020,HUAWEI NOVA 5T RAM 8/128 GARANSI RESMI HUAWEI ...,F2,3.0,PM,Huawei nova 5T,Kota Administrasi Jakarta Barat,False,4589900,16,0,0,0,96,12,19
3,4/29/2020,HUAWEI NOVA 5T RAM 8/128GB GARANSI RESMI HUAWE...,E2,4.0,OS,Huawei nova 5T,Kota Surabaya,False,4698500,5,0,0,0,99,42,63
4,4/15/2020,nokia 3310 reborn,C1,5.0,RM,Nokia 1,Kab. Bangkalan,True,1000000,999999,0,0,3,100,18,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26009,4/27/2020,Asus Zenfone Max Pro M1 - ZB602KL - 4GB/64GB -...,B311,813.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Timur,False,2300000,5,0,0,34,96,99,262
26010,4/8/2020,Asus Zenfone Max Pro M1 Ram 6/64GB Garansi Res...,E417,828.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Pusat,False,2045000,9,4090000,2,65,98,16,29
26011,4/2/2020,Asus Zenfone Max Pro M1 ZB602KL 3/32 GARANSI R...,B676,809.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Pusat,False,1550000,5,0,0,694,98,123,393
26012,4/15/2020,Asus Zenfone Max M1 Pro ZB602KL -6GB/64GB - Ga...,B312,813.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Timur,False,2085000,10,4170000,2,290,96,48,126
26013,4/11/2020,Asus Zenfone Max M1 Pro ZB602KL -6GB/64GB - Ga...,B312,813.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Timur,False,2085000,15,12510000,6,267,96,47,121

In [ ]:
market.isnull().sum()

date              0
sku_name          0
product_id        0
merchant_code     7
merchant_badge    0
product_type      0
merchant_city     0
cod               0
price             0
stock             0
daily_gmv         0
daily_sold        0
daily_view        0
rating            0
total_review      0
total_sold        0
dtype: int64

In [5]:
market.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26014 entries, 0 to 26013
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            26014 non-null  object
 1   sku_name        26014 non-null  object
 2   product_id      26014 non-null  object
 3   merchant_code   26007 non-null  float64
 4   merchant_badge  26014 non-null  object
 5   product_type    26014 non-null  object
 6   merchant_city   26014 non-null  object
 7   cod             26014 non-null  bool
 8   price           26014 non-null  int64
 9   stock           26014 non-null  int64
 10  daily_gmv       26014 non-null  int64
 11  daily_sold      26014 non-null  int64
 12  daily_view      26014 non-null  int64
 13  rating          26014 non-null  int64
 14  total_review    26014 non-null  int64
 15  total_sold      26014 non-null  int64
dtypes: bool(1), float64(1), int64(8), object(6)
memory usage: 3.0+ MB

In [8]:
market.dropna(inplace=True)

In [10]:
market.isnull().sum()

date              0
sku_name          0
product_id        0
merchant_code     0
merchant_badge    0
product_type      0
merchant_city     0
cod               0
price             0
stock             0
daily_gmv         0
daily_sold        0
daily_view        0
rating            0
total_review      0
total_sold        0
dtype: int64

In [13]:
market.describe()

,merchant_code,price,stock,daily_gmv,daily_sold,daily_view,rating,total_review,total_sold
count,26007.000000,2.600700e+04,26007.000000,2.600700e+04,26007.000000,26007.000000,26007.000000,26007.000000,26007.000000
mean,1562.011112,3.890975e+06,344569.522513,1.582571e+06,0.737455,58.829238,98.342985,46.354174,152.456608
std,1041.170081,3.869161e+06,474109.701005,1.603929e+07,7.454425,473.153788,5.452142,91.159704,321.406748
min,1.000000,5.350000e+05,0.000000,-2.342700e+08,-82.000000,0.000000,0.000000,0.000000,0.000000
25%,854.000000,1.770000e+06,4.000000,0.000000e+00,0.000000,2.000000,98.000000,10.000000,27.000000
50%,1252.000000,2.599999e+06,37.000000,0.000000e+00,0.000000,5.000000,100.000000,24.000000,63.000000
75%,2287.000000,4.094950e+06,999972.000000,0.000000e+00,0.000000,21.000000,100.000000,44.000000,144.000000
max,4247.000000,5.000000e+07,999999.000000,9.415350e+08,441.000000,38993.000000,100.000000,2842.000000,7724.000000

In [15]:
market.corr()

<ipython-input-15-668f5995132e>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  market.corr()

,merchant_code,cod,price,stock,daily_gmv,daily_sold,daily_view,rating,total_review,total_sold
merchant_code,1.000000,0.013396,0.051768,0.037770,-0.019525,-0.016225,-0.051417,0.064371,-0.164947,-0.053647
cod,0.013396,1.000000,-0.082113,-0.014202,0.003958,0.032686,0.002797,-0.042983,0.013622,0.018694
price,0.051768,-0.082113,1.000000,0.156706,-0.025671,-0.044618,-0.008936,0.061041,-0.147269,-0.191556
stock,0.037770,-0.014202,0.156706,1.000000,-0.063246,-0.064972,-0.075292,0.033286,-0.134122,-0.174839
daily_gmv,-0.019525,0.003958,-0.025671,-0.063246,1.000000,0.880633,0.676940,0.003093,0.157915,0.190790
daily_sold,-0.016225,0.032686,-0.044618,-0.064972,0.880633,1.000000,0.537999,-0.001377,0.162829,0.232260
daily_view,-0.051417,0.002797,-0.008936,-0.075292,0.676940,0.537999,1.000000,-0.008496,0.222010,0.177663
rating,0.064371,-0.042983,0.061041,0.033286,0.003093,-0.001377,-0.008496,1.000000,-0.060147,-0.043073
total_review,-0.164947,0.013622,-0.147269,-0.134122,0.157915,0.162829,0.222010,-0.060147,1.000000,0.782728
total_sold,-0.053647,0.018694,-0.191556,-0.174839,0.190790,0.232260,0.177663,-0.043073,0.782728,1.000000

In [16]:
!pip install streamlit==1.14.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting streamlit==1.14.0
  Downloading streamlit-1.14.0-py2.py3-none-any.whl (9.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 41.9 MB/s eta 0:00:00
Collecting pydeck>=0.1.dev5
  Downloading pydeck-0.8.1b0-py2.py3-none-any.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 79.5 MB/s eta 0:00:00
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (13.3.4)
Requirement already satisfied: pyarrow>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (9.0.0)
Collecting validators>=0.2
  Downloading validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tornado>=5.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (6.2)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (8.1.3)
Collecting pympler>=0.9
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 13.2 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.10.0.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (4.5.0)
Collecting blinker>=1.0.0
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (2.8.2)
Requirement already satisfied: requests>=2.4 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (2.27.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (8.4.0)
Collecting importlib-metadata>=1.4
  Downloading importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Requirement already satisfied: packaging>=14.1 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (23.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (1.22.4)
Requirement already satisfied: cachetools>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (5.3.0)
Requirement already satisfied: toml in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (0.10.2)
Collecting watchdog
  Downloading watchdog-3.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 12.1 MB/s eta 0:00:00
Collecting gitpython!=3.1.19
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 23.6 MB/s eta 0:00:00
Requirement already satisfied: altair>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (4.2.2)
Requirement already satisfied: tzlocal>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (4.3)
Requirement already satisfied: pandas>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (1.5.3)
Collecting semver
  Downloading semver-3.0.0-py3-none-any.whl (17 kB)
Requirement already satisfied: protobuf<4,>=3.12 in /usr/local/lib/python3.10/dist-packages (from streamlit==1.14.0) (3.20.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair>=3.2.0->streamlit==1.14.0) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair>=3.2.0->streamlit==1.14.0) (3.1.2)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair>=3.2.0->streamlit==1.14.0) (0.12.0)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair>=3.2.0->streamlit==1.14.0) (4.3.3)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=1.4->streamlit==1.14.0) (3.15.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.21.0->streamlit==1.14.0) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil->streamlit==1.14.0) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.4->streamlit==1.14.0) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.4->streamlit==1.14.0) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.4->streamlit==1.14.0) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.4->streamlit==1.14.0) (2.0.12)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->streamlit==1.14.0) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->streamlit==1.14.0) (2.14.0)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.10/dist-packages (from tzlocal>=1.1->streamlit==1.14.0) (0.1.0.post0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from validators>=0.2->streamlit==1.14.0) (4.4.2)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair>=3.2.0->streamlit==1.14.0) (2.1.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit==1.14.0) (0.19.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit==1.14.0) (23.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit==1.14.0) (0.1.2)
Requirement already satisfied: tzdata in /usr/local/lib/python3.10/dist-packages (from pytz-deprecation-shim->tzlocal>=1.1->streamlit==1.14.0) (2023.3)
Building wheels for collected packages: validators
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=45953984bd624d278e7ed146d4297a886b762f19d5edc81feb3ceed89548fd86
  Stored in directory: /root/.cache/pip/wheels/f2/ed/dd/d3a556ad245ef9dc570c6bcd2f22886d17b0b408dd3bbb9ac3
Successfully built validators
Installing collected packages: watchdog, validators, smmap, semver, pympler, importlib-metadata, blinker, pydeck, gitdb, gitpython, streamlit
Successfully installed blinker-1.6.2 gitdb-4.0.10 gitpython-3.1.31 importlib-metadata-6.6.0 pydeck-0.8.1b0 pympler-1.0.1 semver-3.0.0 smmap-5.0.0 streamlit-1.14.0 validators-0.20.0 watchdog-3.0.0

In [21]:
%%writefile home.py
import streamlit as st
import pandas as pd
import altair as alt
import plotly.express as px
if st.button('welcome to our page'):
    st.write(' hello')
else:
    st.write('Goodbye')
sreen = st.sidebar.selectbox("select the page:",["page1","page2","page3"])
market = pd.read_csv('marketplace.csv')
if sreen == "page1":
       st.title('Air Traffic Application')
       st.text('San Francisco International Airport Report on Monthly Passenger Traffic Statistics by Airline')
acti = st.selectbox("Select Operating Airline",market['sku_name'].unique())
st.write(acti)
plot_type=st.radio("select the plot type",['scatter','line'])
if plot_type =='scatter':
  pl = alt.Chart(market[market['sku_name']==acti]).mark_circle().encode(
    x = 'total_sold',
    y ='total_review',
    tooltip = ['total_sold','total_review']
).interactive()
else:
      pl = alt.Chart(market[market['sku_name']==acti]).mark_line().encode(
    x = 'total_sold',
    y ='total_review',
    tooltip = ['total_sold','total_review']
).interactive()
st.altair_chart(pl)

Overwriting home.py

In [22]:
!streamlit run home.py &>/dev/null&
!npx localtunnel --port 8501

npx: installed 22 in 2.768s
your url is: https://cyan-wings-follow.loca.lt
^C

In [18]:
market

,date,sku_name,product_id,merchant_code,merchant_badge,product_type,merchant_city,cod,price,stock,daily_gmv,daily_sold,daily_view,rating,total_review,total_sold
0,3/11/2020,HUAWEI NOVA 5T RAM 8GB INTERNAL 128GB,E1,1.0,PM,Huawei nova 5T,Kota Kediri,False,4500000,1,0,0,0,95,37,74
1,3/26/2020,Huawei Nova 5T (8GB/128GB) - Crush Green,F1,2.0,OS,Huawei nova 5T,Kota Administrasi Jakarta Utara,False,4999000,5,0,0,0,0,0,2
2,3/23/2020,HUAWEI NOVA 5T RAM 8/128 GARANSI RESMI HUAWEI ...,F2,3.0,PM,Huawei nova 5T,Kota Administrasi Jakarta Barat,False,4589900,16,0,0,0,96,12,19
3,4/29/2020,HUAWEI NOVA 5T RAM 8/128GB GARANSI RESMI HUAWE...,E2,4.0,OS,Huawei nova 5T,Kota Surabaya,False,4698500,5,0,0,0,99,42,63
4,4/15/2020,nokia 3310 reborn,C1,5.0,RM,Nokia 1,Kab. Bangkalan,True,1000000,999999,0,0,3,100,18,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26009,4/27/2020,Asus Zenfone Max Pro M1 - ZB602KL - 4GB/64GB -...,B311,813.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Timur,False,2300000,5,0,0,34,96,99,262
26010,4/8/2020,Asus Zenfone Max Pro M1 Ram 6/64GB Garansi Res...,E417,828.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Pusat,False,2045000,9,4090000,2,65,98,16,29
26011,4/2/2020,Asus Zenfone Max Pro M1 ZB602KL 3/32 GARANSI R...,B676,809.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Pusat,False,1550000,5,0,0,694,98,123,393
26012,4/15/2020,Asus Zenfone Max M1 Pro ZB602KL -6GB/64GB - Ga...,B312,813.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Timur,False,2085000,10,4170000,2,290,96,48,126
26013,4/11/2020,Asus Zenfone Max M1 Pro ZB602KL -6GB/64GB - Ga...,B312,813.0,OS,Asus Zenfone Max Pro (M1) ZB601KL/ZB602K,Kota Administrasi Jakarta Timur,False,2085000,15,12510000,6,267,96,47,121

In [23]:
%%writefile page2.py
import streamlit as st
import pandas as pd
import altair as alt
import matplotlib.pyplot as plt
import plotly.express as px
market = pd.read_csv('marketplace.csv')
st.title('Air Traffic Application')

number = st.number_input('what you Suggest the number of Passenger Count')
st.write('The current number is ', number)
pie_chart = px.pie(market, 
            title='number of Passenger with the GEO Region',
            values='price',
            names='GEO Region')
st.plotly_chart(pie_chart)

Writing page2.py

In [ ]:
!streamlit run page2.py &>/dev/null&
!npx localtunnel --port 8501

npx: installed 22 in 2.744s
your url is: https://smart-lions-walk.loca.lt